// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// AuthMailer is an autogenerated mock type for the Mailer type
type AuthMailer struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, to, subject, text, html
func (_m *AuthMailer) Send(ctx context.Context, to string, subject string, text io.Reader, html io.Reader) error {
	ret := _m.Called(ctx, to, subject, text, html)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, io.Reader) error); ok {
		r0 = rf(ctx, to, subject, text, html)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAuthMailer interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthMailer creates a new instance of AuthMailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthMailer(t mockConstructorTestingTNewAuthMailer) *AuthMailer {
	mock := &AuthMailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
